---
- name: restart webserver
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
  when: php_enable_php_fpm

- name: restart php-fpm
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
  when: php_enable_php_fpm

